"""Phase 7R "Source H": build hybrid training rows from the base model's OWN organic thinking traces,
with a spliced decision trigger -- see reports/16/17/19 and build_phase7r.py/train_phase7.py (reused, not
re-implemented: exact call-expansion format, chat-template rendering technique, masked-span accounting,
encode_think's masking contract).

Why: authored-prose Stage A/B rows (build_phase7r.py) did not transfer a natural trigger rate (2.3%,
reports/19 arm B finding). Source H instead takes the base model's own organic `thinking` (generated by
scripts/gen_think_traces.py over oracle/phase7r-hybrid-prompts.jsonl -- 1250 train prompts) and SPLICES
a typed trigger into it at a natural decision-commitment point, dropping everything the organic trace said
after that point (that's where the token saving comes from) and replacing it with the canonical injected
call + a short "So it's {label}." style tail, so the model's own voice/register survives everywhere except
the spliced boundary.

DEV SAFETY: oracle/phase7r-hybrid-organic.jsonl (the real Source H input) was still generating on a GPU box
at the time this was written. Development/testing happens against oracle/t3-armB-think.fixed.jsonl instead
(same row schema -- see module-level ROW FORMAT note below) -- it is EVAL data (same ids as
oracle/phase7r-natural-eval.jsonl, joined by id in scripts/extract_labels_llm.py) and must NEVER leak into
a real training output. `build` therefore refuses to run if any input row's id or item_ref is present in
oracle/phase7r-natural-eval.jsonl, UNLESS --dev is passed; --dev additionally refuses to write anywhere
--out doesn't contain the literal substring "dev" (case-insensitive), so a dev run cannot overwrite a real
training file by accident.

ROW FORMAT (organic input, one line per row): every key gen_think_traces.py passes through from
oracle/phase7r-hybrid-prompts.jsonl (id, user, kind in {"decision","control"} (dev file also has
"adversarial"; treated the same as "control" here -- no gold_label to splice against), type, gold_label,
options_with_descriptions, item_ref, label_surfaces) PLUS thinking/answer/raw_text/n_thinking_tokens/
n_answer_tokens/finished.

Row filter (rule 1): finished, non-empty thinking+answer, n_thinking_tokens <= 900. Decision rows
additionally require the organic ANSWER to agree with gold_label -- judged by `--extract FILE`
(scripts/extract_labels_llm.py output, keyed by id) when given, else a word-boundary regex fallback over
leak_terms(key) (check_phase7r_pilot.py's SYNONYMS/leak_terms, reused) for the gold label vs every other
option; disagreements/ambiguous-signal rows are dropped and counted per type (rule 1).

Splice (rule 2, decision rows only): scan `thinking` line by line; the first line whose text contains a
leak_terms hit for gold_label, EXCLUDING lines that merely enumerate options (>=2 distinct option keys
named in one line), is the "commit line". If that line starts before char 150, or no such line exists, the
row is dropped (no valid splice point). Otherwise the char offset of that line's start is the splice point:
everything in `thinking` from there on is dropped and replaced with
`<|decide:TYPE|>{injected}{tail}`, where `injected` is build_phase7r.py's exact
"{instruction} [{described options}]<|result|>{gold}<|/result|>" (same function, build_reasoning, reused)
and `tail` is one of ~12 short templates naming the label naturally, chosen deterministically per row id.
The organic ANSWER is kept verbatim; thinking_long = the unmodified organic thinking (token-saving
comparison baseline).

Control rows (rule 3, kind != "decision"): kept with organic thinking+answer completely unchanged, no
trigger -- teaches the model not to fire the trigger on ordinary turns.

Output schema (rule 4): the same per-row schema build_phase7r.py's assemble_row emits (so
train_phase7.py's encode_think / --think-calls --think-variant short works unchanged on this file), plus
source="H", organic_thinking_tokens, hybrid_thinking_tokens, saved_tokens, splice_char.

Usage (laptop, CPU, tokenizer only):
    python scripts/build_phase7r_hybrid.py build --organic oracle/t3-armB-think.fixed.jsonl \\
        --out oracle/phase7r-hybrid-dev-built.jsonl --dev
    python scripts/build_phase7r_hybrid.py validate --rows oracle/phase7r-hybrid-dev-built.jsonl --dev
"""
import argparse
import collections
import json
import os
import random
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from kev.api import option_text  # noqa: E402
from scripts.check_phase7r_pilot import (  # noqa: E402 -- reused, not copied
    NONE_KEY, RESULT_CLOSE, RESULT_OPEN, SYNONYMS, SUITE, TYPE_SOURCE, leak_terms, load_canonical,
)
from scripts.build_phase7r import (  # noqa: E402 -- reused, not copied
    MODEL, REVISION, SHIPPED_TYPES, TRIGGER_FOR, build_reasoning, get_tokenizer,
    injected_spans_typed, token_accounting,
)
from scripts.gen_think_traces import (  # noqa: E402 -- reused, not copied
    THINK_CLOSE, THINK_OPEN, _strip_pad_and_turn,
)

NATURAL_EVAL = "oracle/phase7r-natural-eval.jsonl"

MAX_THINK_TOKENS = 900
MIN_SPLICE_CHARS = 150

TAIL_TEMPLATES = [
    "So it's {label}.",
    "That settles it: {label}.",
    "The answer here is {label}.",
    "This resolves to {label}.",
    "Putting it together, this is {label}.",
    "Conclusion: {label}.",
    "On balance, it comes down to {label}.",
    "So the call here is {label}.",
    "That points to {label}.",
    "Given all that, {label} is the right call.",
    "In short, this is {label}.",
    "So the decision is {label}.",
]


def label_surface(label):
    return label.replace("_", " ")


def tail_for(row_id, label):
    rng = random.Random(f"{row_id}:{label}")
    tmpl = rng.choice(TAIL_TEMPLATES)
    return tmpl.format(label=label_surface(label))


# ---------------------------------------------------------------------------
# dev-leak guard
# ---------------------------------------------------------------------------

def load_eval_keys(path):
    ids, item_refs = set(), set()
    if not os.path.exists(path):
        return ids, item_refs
    with open(path, encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            rec = json.loads(line)
            if rec.get("id"):
                ids.add(rec["id"])
            if rec.get("item_ref"):
                item_refs.add(rec["item_ref"])
    return ids, item_refs


def guard_dev_leak(rows, eval_ids, eval_refs, dev, out_path):
    hit_ids = [r["id"] for r in rows if r.get("id") in eval_ids or r.get("item_ref") in eval_refs]
    if hit_ids and not dev:
        raise SystemExit(
            f"REFUSING: {len(hit_ids)} input row(s) have an id/item_ref present in {NATURAL_EVAL} "
            f"(eval data) -- e.g. {hit_ids[:5]}. Pass --dev if this is an intentional development run "
            f"against eval-shaped data (--dev also requires --out to contain 'dev').")
    if dev and "dev" not in os.path.basename(out_path).lower():
        raise SystemExit(
            f"--dev requires --out to contain the substring 'dev' in its filename (got {out_path!r})")
    return len(hit_ids)


# ---------------------------------------------------------------------------
# agreement check (rule 1)
# ---------------------------------------------------------------------------

def _word_hit(terms, text_lower):
    return any(re.search(r"\b" + re.escape(t) + r"\b", text_lower) for t in terms if t)


def load_extract(path):
    if not path:
        return {}
    out = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rec = json.loads(line)
                out[rec["id"]] = rec
    return out


def check_agreement(row, extract_by_id):
    """-> (agree: bool|None, reason: str). None means "no reliable signal; drop"."""
    gold = row["gold_label"]
    ext = extract_by_id.get(row["id"])
    if ext is not None:
        return (ext.get("chosen") == gold), "extract"

    answer_l = row["answer"].lower()
    gold_hit = _word_hit(leak_terms(gold), answer_l)
    other_hits = [k for k, _d in row["options_with_descriptions"] if k != gold
                  and _word_hit(leak_terms(k), answer_l)]
    if gold_hit and not other_hits:
        return True, "regex_agree"
    if not gold_hit and other_hits:
        return False, "regex_disagree"
    if gold_hit and other_hits:
        return False, "regex_ambiguous"
    return None, "regex_no_signal"


# ---------------------------------------------------------------------------
# splice point (rule 2)
# ---------------------------------------------------------------------------

def _key_variants(key):
    return {key.lower(), key.lower().replace("_", " "), key.lower().replace("_", "-")}


def find_splice(thinking, gold, option_keys, min_chars=MIN_SPLICE_CHARS):
    """-> (offset: int|None, reason: str). offset is the char index in `thinking` where the commit line
    starts (the splice point); None + a reason explains why no valid splice point exists."""
    gold_terms = leak_terms(gold)
    lines = thinking.split("\n")
    offset = 0
    for line in lines:
        line_l = line.lower()
        if _word_hit(gold_terms, line_l):
            enum_count = sum(1 for k in option_keys if any(_word_hit([v], line_l) for v in _key_variants(k)))
            if enum_count >= 2:
                offset += len(line) + 1
                continue  # enumeration line (names >=2 options), not a real commitment -- keep scanning
            if offset < min_chars:
                return None, "commit_too_early"
            return offset, "ok"
        offset += len(line) + 1
    return None, "no_commit_line"


# ---------------------------------------------------------------------------
# splice point for `prefix` mode (rule A) -- generalized for answer_type/kb_category/news_topic, whose
# prompts never list the canonical option keys, so the base model's organic thinking enumerates
# candidates in ITS OWN taxonomy ("Food and Drink", "Organized Crime", ...), not the suite's option
# vocabulary -- find_splice's gold/option-key word-hit approach therefore almost never fires on these rows
# (rule 1's ~70% agreement-drop in the module docstring). Instead: split `thinking` into TOP-LEVEL
# numbered steps (lines matching STEP_RE), find the first line anywhere whose (markdown-stripped) text
# matches PREFIX_TRIGGER_RE -- phrasing the model reliably uses right before it starts naming/listing
# candidate categories/answer-types/tags ("Potential Answer Categories", "Determine the Best Answer
# Type", "Conclusion:", ...) -- and cut at the START of the top-level step that line falls inside (never
# mid-bullet, mid-sentence: the only valid cut points are top-level step boundaries, which are always
# preceded by a newline in this data). Preference: keep the first min(enum_step_idx, 3) steps (reports/16
# "2nd-3rd analysis step" preference), but only once that boundary reaches >=150 chars; if even the
# step right before the enumeration step is short of 150 chars, there wasn't enough restating/
# understanding before the model started naming candidates and the row has no valid splice."""
STEP_RE = re.compile(r"^(\d+)\.\s", re.M)
PREFIX_TRIGGER_RE = re.compile(
    "|".join([
        r"potential\s+(answer|categor|audienc|use[\s-]?case)",
        r"determine\s+(the\s+)?potential",
        r"identify\s+potential",
        r"evaluate\s+.*\bcategor",
        r"select the (most|best)",
        r"choose the (most|best)",
        r"determine the (best|most|appropriate|likely)\b",
        r"final (tag|category|answer|selection)",
        r"formulate the answer",
        r"\bconclusion\b",
        r"classify the answer",
        r"tag selection",
        r"best fit",
        r"most (precise|specific|appropriate|accurate) categor",
        r"select (the )?appropriate",
        r"identify the best answer",
        r"answer type categor",
        r"best answer type",
    ]), re.I)


def find_splice_prefix(thinking, min_chars=MIN_SPLICE_CHARS, prefer_step=3):
    """-> (offset: int|None, reason: str). See module note above `STEP_RE`/`PREFIX_TRIGGER_RE` for the
    algorithm; offset is always the char index of a top-level numbered step's start (never mid-line)."""
    starts = [m.start() for m in STEP_RE.finditer(thinking)]
    if not starts:
        return None, "no_steps"
    starts_ext = starts + [len(thinking)]

    lines = thinking.split("\n")
    line_offsets, pos = [], 0
    for ln in lines:
        line_offsets.append(pos)
        pos += len(ln) + 1

    trig_off = None
    for off, ln in zip(line_offsets, lines):
        if PREFIX_TRIGGER_RE.search(ln.replace("*", "")):
            trig_off = off
            break
    if trig_off is None:
        return None, "no_enumeration_found"

    enum_idx = None
    for i in range(len(starts)):
        if starts[i] <= trig_off < starts_ext[i + 1]:
            enum_idx = i
            break
    if enum_idx is None:
        return None, "commit_too_early_preamble"  # trig_off falls before the first numbered step
    if enum_idx == 0:
        return None, "commit_too_early_step0"  # enumeration starts in step 1 itself -- no room to splice

    target_idx = min(enum_idx, prefer_step)
    while target_idx >= 1 and starts[target_idx] < min_chars:
        target_idx += 1
        if target_idx > enum_idx:
            return None, "commit_too_early"
    return starts[target_idx], "ok"


# ---------------------------------------------------------------------------
# rendering (no system turn -- gen_think_traces.py's render_prompt never supplies one for these prompts)
# ---------------------------------------------------------------------------

def render_hybrid(tok, user, reasoning, answer):
    messages = [{"role": "user", "content": user}]
    prompt = tok.apply_chat_template(messages, tokenize=False, add_generation_prompt=True,
                                      enable_thinking=True)
    full = tok.apply_chat_template(
        messages + [{"role": "assistant", "content": answer, "reasoning": reasoning}],
        tokenize=False, add_generation_prompt=False, enable_thinking=True)
    if not full.startswith(prompt):
        raise ValueError("chat template render did not produce prompt as an exact prefix")
    return full, len(prompt)


def decoded_think_tokens(tok, text):
    """Decoded (non-injected) token count of a thinking string in isolation -- used for the
    organic/hybrid/saved token accounting fields; injected spans never appear in a bare `thinking` string
    by construction (the trigger+injected text is only ever assembled inside build_hybrid_row)."""
    return len(tok(text, add_special_tokens=False)["input_ids"])


# ---------------------------------------------------------------------------
# build
# ---------------------------------------------------------------------------

def build_hybrid_row(tok, row, canonical, splice_offset=None):
    """row: one organic trace dict (filtered, agreed if decision). canonical: {type: (instr, opt_keys)}
    from check_phase7r_pilot.load_canonical. Returns the output row dict (rule 4 schema), or raises for a
    genuine bug (never for a drop condition -- callers decide drops before calling this)."""
    is_decision = row["kind"] == "decision"
    user, answer, thinking = row["user"], row["answer"], row["thinking"]

    if is_decision:
        gold, tname = row["gold_label"], row["type"]
        options_kv = row["options_with_descriptions"]
        instr, _opts = canonical[tname]
        options = [option_text(k, d) for k, d in options_kv]
        calls = [{"type": tname, "instruction": instr, "options": options, "gold_label": gold}]
        kept = thinking[:splice_offset].rstrip()
        tail = tail_for(row["id"], gold)
        segs = [kept, tail]
        reasoning_short = build_reasoning(calls, segs)
        decision_types = [tname]
        label_surfaces = {gold: label_surface(gold)}
        kind = "call"
    else:
        calls, segs, decision_types, label_surfaces, kind = [], [thinking], [], {}, "control"
        reasoning_short = thinking

    reasoning_long = thinking

    full_short, plen_short = render_hybrid(tok, user, reasoning_short, answer)
    full_long, plen_long = render_hybrid(tok, user, reasoning_long, answer)

    injected = injected_spans_typed(full_short)
    if injected_spans_typed(full_long):
        raise ValueError(f"{row['id']}: thinking_long contains trigger/result markers")
    if is_decision and len(injected) != 1:
        raise ValueError(f"{row['id']}: expected exactly 1 injected span, found {len(injected)}")
    if not is_decision and injected:
        raise ValueError(f"{row['id']}: control row has {len(injected)} injected span(s)")

    acct_short = token_accounting(tok, full_short, plen_short, injected)
    acct_long = token_accounting(tok, full_long, plen_long, [])
    masked_spans_short = [[0, plen_short]] + [[s, e] for s, e in injected]

    organic_tok = decoded_think_tokens(tok, thinking)
    hybrid_tok = decoded_think_tokens(tok, reasoning_short) if is_decision else organic_tok

    return {
        "id": row["id"], "kind": kind, "source": "H", "decision_types": decision_types,
        "adversarial": row["kind"] == "adversarial", "user": user,
        "calls": calls, "label_surfaces": label_surfaces, "answer": answer,
        "thinking_segments": segs, "thinking_long": reasoning_long,
        "target_text_short": full_short, "target_text_long": full_long,
        "masked_spans_short": masked_spans_short,
        "tokens_short": acct_short, "tokens_long": acct_long,
        "delta_supervised": acct_long["tokens_supervised"] - acct_short["tokens_supervised"],
        "delta_total": (acct_long["tokens_total"] - acct_long["tokens_prompt_masked"]) -
                        (acct_short["tokens_total"] - acct_short["tokens_prompt_masked"]),
        "organic_thinking_tokens": organic_tok, "hybrid_thinking_tokens": hybrid_tok,
        "saved_tokens": organic_tok - hybrid_tok,
        "splice_char": splice_offset if is_decision else None,
    }


def build(args):
    organic_path = args.organic if os.path.isabs(args.organic) else os.path.join(ROOT, args.organic)
    out_path = args.out if os.path.isabs(args.out) else os.path.join(ROOT, args.out)
    natural_path = os.path.join(ROOT, NATURAL_EVAL)

    rows = [json.loads(l) for l in open(organic_path, encoding="utf-8") if l.strip()]
    if args.limit:
        rows = rows[:args.limit]
    print(f"loaded {len(rows)} rows from {args.organic}")

    eval_ids, eval_refs = load_eval_keys(natural_path)
    n_dev_hits = guard_dev_leak(rows, eval_ids, eval_refs, args.dev, out_path)
    if n_dev_hits:
        print(f"--dev: {n_dev_hits} input rows overlap {NATURAL_EVAL} by id/item_ref (expected for "
              f"development against eval-shaped data; NOT written unless --dev)")

    canonical, canon_errs = load_canonical(os.path.join(ROOT, SUITE))
    if canon_errs:
        raise SystemExit(f"load_canonical errors: {canon_errs}")

    extract_by_id = load_extract(args.extract if not args.extract or os.path.isabs(args.extract)
                                  else os.path.join(ROOT, args.extract))

    tok = get_tokenizer(args.model, args.revision)

    drop_reasons = collections.Counter()
    drop_by_type = collections.defaultdict(collections.Counter)
    kept = []
    examples_by_reason = collections.defaultdict(list)

    for row in rows:
        rid, rtype = row["id"], row.get("type")
        if not row.get("finished"):
            drop_reasons["not_finished"] += 1
            drop_by_type[rtype]["not_finished"] += 1
            continue
        if not row.get("thinking") or not row.get("answer"):
            drop_reasons["empty_thinking_or_answer"] += 1
            drop_by_type[rtype]["empty_thinking_or_answer"] += 1
            continue
        if row.get("n_thinking_tokens", 0) > MAX_THINK_TOKENS:
            drop_reasons["over_max_think_tokens"] += 1
            drop_by_type[rtype]["over_max_think_tokens"] += 1
            continue

        if row["kind"] != "decision":
            built = build_hybrid_row(tok, row, canonical)
            kept.append(built)
            continue

        agree, reason = check_agreement(row, extract_by_id)
        if agree is not True:
            tag = "disagree" if agree is False else "no_signal"
            drop_reasons[tag] += 1
            drop_by_type[rtype][tag] += 1
            if len(examples_by_reason[tag]) < 2:
                examples_by_reason[tag].append((rid, reason, row["gold_label"], row["answer"][:200]))
            continue

        option_keys = [k for k, _d in row["options_with_descriptions"]]
        splice_offset, splice_reason = find_splice(row["thinking"], row["gold_label"], option_keys)
        if splice_offset is None:
            drop_reasons[f"no_splice:{splice_reason}"] += 1
            drop_by_type[rtype][f"no_splice:{splice_reason}"] += 1
            if len(examples_by_reason[f"no_splice:{splice_reason}"]) < 2:
                examples_by_reason[f"no_splice:{splice_reason}"].append(
                    (rid, splice_reason, row["gold_label"], row["thinking"][:300]))
            continue

        built = build_hybrid_row(tok, row, canonical, splice_offset=splice_offset)
        kept.append(built)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        for r in kept:
            f.write(json.dumps(r) + "\n")

    # ---- summary ----
    n_decision_in = sum(1 for r in rows if r["kind"] == "decision")
    n_control_in = len(rows) - n_decision_in
    n_kept_call = sum(1 for r in kept if r["kind"] == "call")
    n_kept_ctrl = sum(1 for r in kept if r["kind"] == "control")
    print(f"\nbuilt {len(kept)} rows -> {out_path}")
    print(f"  input: {len(rows)} ({n_decision_in} decision, {n_control_in} control/adversarial)")
    print(f"  kept:  {len(kept)} ({n_kept_call} call, {n_kept_ctrl} control)")
    print(f"  dropped: {sum(drop_reasons.values())}, by reason: {dict(drop_reasons)}")
    print("  dropped by type:")
    for t, ctr in sorted(drop_by_type.items()):
        print(f"    {t}: {dict(ctr)}")

    decision_per_type = collections.Counter(r.get("type") for r in rows if r["kind"] == "decision")
    kept_decision_ids = {r["id"] for r in kept if r["kind"] == "call"}
    for t in sorted(decision_per_type):
        n_in = decision_per_type[t]
        n_out = sum(1 for r in kept if r["kind"] == "call" and r["decision_types"] == [t])
        n_disagree = drop_by_type[t].get("disagree", 0) + drop_by_type[t].get("no_signal", 0)
        print(f"  type {t}: {n_in} in -> {n_out} kept, {n_disagree} agreement-dropped "
              f"({n_disagree/n_in:.1%})" if n_in else f"  type {t}: 0 in")

    call_rows = [r for r in kept if r["kind"] == "call"]
    if call_rows:
        org = [r["organic_thinking_tokens"] for r in call_rows]
        hyb = [r["hybrid_thinking_tokens"] for r in call_rows]
        saved = [r["saved_tokens"] for r in call_rows]
        mean_org, mean_hyb, mean_saved = sum(org) / len(org), sum(hyb) / len(hyb), sum(saved) / len(saved)
        print(f"\n  thinking tokens: organic mean {mean_org:.1f}, hybrid mean {mean_hyb:.1f}, "
              f"saved mean {mean_saved:.1f} ({mean_saved / mean_org:.1%})")

    for reason, examples in sorted(examples_by_reason.items()):
        print(f"\n  examples for drop reason {reason!r}:")
        for rid, why, gold, snippet in examples:
            print(f"    {rid} gold={gold!r} ({why}): {snippet!r}")

    if call_rows:
        print("\n  3 decoded examples around the splice:")
        for r in call_rows[:3]:
            trig = TRIGGER_FOR[r["decision_types"][0]]
            idx = r["target_text_short"].find(trig)
            lo, hi = max(0, idx - 150), idx + len(trig) + 200
            print(f"\n    {r['id']} splice_char={r['splice_char']} saved={r['saved_tokens']}:")
            print(f"    ...{r['target_text_short'][lo:hi]!r}...")

    return kept


# ---------------------------------------------------------------------------
# prefix mode (rule A): organic trace -> spliced prefill, no continuation yet (that is
# scripts/continue_phase7r_hybrid.py's job -- GPU required, not available on this box).
# ---------------------------------------------------------------------------

def render_prompt_only(tok, user):
    """Same render as gen_think_traces.render_prompt for these rows (no `system` turn -- the organic
    prompts this builder consumes never carry one; see gen_think_traces.py's row schema note)."""
    messages = [{"role": "user", "content": user}]
    return tok.apply_chat_template(messages, tokenize=False, add_generation_prompt=True,
                                    enable_thinking=True)


def build_prefix_row(tok, row, canonical, splice_offset):
    tname, gold = row["type"], row["gold_label"]
    instr, _opts = canonical[tname]
    options_kv = row["options_with_descriptions"]
    options = [option_text(k, d) for k, d in options_kv]
    calls = [{"type": tname, "instruction": instr, "options": options, "gold_label": gold}]
    organic_kept = row["thinking"][:splice_offset].rstrip()
    prefix_core = build_reasoning(calls, [organic_kept, ""])  # kept + TRIGGER + injected + "" (no tail)
    return {
        "id": row["id"], "type": tname, "gold_label": gold,
        "options_with_descriptions": options_kv, "item_ref": row.get("item_ref"),
        "label_surfaces": row.get("label_surfaces"), "user": row["user"],
        "prompt_text": render_prompt_only(tok, row["user"]),
        "prefix_text": THINK_OPEN + prefix_core,
        "organic_kept": organic_kept, "splice_char": splice_offset,
        "thinking_long": row["thinking"], "organic_answer": row["answer"],
    }


def prefix_mode(args):
    organic_path = args.organic if os.path.isabs(args.organic) else os.path.join(ROOT, args.organic)
    out_path = args.out if os.path.isabs(args.out) else os.path.join(ROOT, args.out)

    rows = [json.loads(l) for l in open(organic_path, encoding="utf-8") if l.strip()]
    if args.limit:
        rows = rows[:args.limit]
    dec_rows = [r for r in rows if r["kind"] == "decision"]
    print(f"loaded {len(rows)} rows ({len(dec_rows)} decision) from {args.organic}")

    canonical, canon_errs = load_canonical(os.path.join(ROOT, SUITE))
    if canon_errs:
        raise SystemExit(f"load_canonical errors: {canon_errs}")

    tok = get_tokenizer(args.model, args.revision)

    splice_reasons = collections.Counter()
    kept = []
    for row in dec_rows:
        thinking = row.get("thinking") or ""
        if not thinking:
            splice_reasons["empty_thinking"] += 1
            continue
        off, reason = find_splice_prefix(thinking)
        splice_reasons[reason] += 1
        if off is None:
            continue
        kept.append(build_prefix_row(tok, row, canonical, off))

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        for r in kept:
            f.write(json.dumps(r) + "\n")

    print(f"\nprefix: {len(kept)}/{len(dec_rows)} decision rows got a valid splice -> {out_path}")
    print(f"  splice reasons (incl. 'ok'): {dict(splice_reasons)}")
    if kept:
        chars = sorted(r["splice_char"] for r in kept)
        fracs = sorted(r["splice_char"] / len(r["thinking_long"]) for r in kept)
        n = len(chars)
        print(f"  splice_char: min={chars[0]} p50={chars[n // 2]} max={chars[-1]}")
        print(f"  fraction of organic thinking kept: min={fracs[0]:.2f} p50={fracs[n // 2]:.2f} "
              f"max={fracs[-1]:.2f}")
        print("\n  3 examples around the splice (tail of prefix_text):")
        for r in kept[:3]:
            print(f"\n    {r['id']} splice_char={r['splice_char']}:")
            print(f"    ...{r['prefix_text'][-300:]!r}")
    return kept


# ---------------------------------------------------------------------------
# build2 mode (rule C): join prefixes + continuations (scripts/continue_phase7r_hybrid.py's output) into
# final training rows, same schema as `build`'s output (source="H", so train_phase7.py's encode_think
# works unchanged).
# ---------------------------------------------------------------------------

def build2_row(tok, prow, cont_text, canonical):
    """-> (row dict, mention_bool) or raises ValueError for a drop condition the caller matches on
    message prefix (keeps the drop-reason bookkeeping in one place, in build2())."""
    if "<|decide:" in cont_text:
        raise ValueError("retrigger: continuation contains a second '<|decide:' trigger")
    close_idx = cont_text.find(THINK_CLOSE)
    if close_idx < 0:
        raise ValueError("no_close_marker: continuation never closes the thinking channel")
    if cont_text.find(THINK_CLOSE, close_idx + len(THINK_CLOSE)) >= 0:
        raise ValueError("malformed_channel: thinking channel closed more than once")
    if THINK_OPEN in cont_text:
        raise ValueError("malformed_channel: continuation reopens the thinking channel")

    thinking_tail = cont_text[:close_idx]
    answer = _strip_pad_and_turn(cont_text[close_idx + len(THINK_CLOSE):])
    if not answer:
        raise ValueError("empty_answer: continuation has no visible answer after the thinking channel")

    tname, gold = prow["type"], prow["gold_label"]
    instr, _opts = canonical[tname]
    options = [option_text(k, d) for k, d in prow["options_with_descriptions"]]
    calls = [{"type": tname, "instruction": instr, "options": options, "gold_label": gold}]

    reasoning_short = build_reasoning(calls, [prow["organic_kept"], thinking_tail])
    reasoning_long = prow["thinking_long"]

    full_short, plen_short = render_hybrid(tok, prow["user"], reasoning_short, answer)
    full_long, plen_long = render_hybrid(tok, prow["user"], reasoning_long, prow["organic_answer"])

    injected = injected_spans_typed(full_short)
    if injected_spans_typed(full_long):
        raise ValueError(f"{prow['id']}: thinking_long contains trigger/result markers")
    if len(injected) != 1:
        raise ValueError(f"bad_injected_spans: expected 1 injected span, found {len(injected)}")

    acct_short = token_accounting(tok, full_short, plen_short, injected)
    acct_long = token_accounting(tok, full_long, plen_long, [])
    masked_spans_short = [[0, plen_short]] + [[s, e] for s, e in injected]

    organic_tok = decoded_think_tokens(tok, reasoning_long)
    hybrid_tok = decoded_think_tokens(tok, reasoning_short)

    check_text = (thinking_tail + " " + answer).lower()
    terms = set(leak_terms(gold))
    mentioned = any(_word_hit([t], check_text) for t in terms if t)

    row = {
        "id": prow["id"], "kind": "call", "source": "H", "decision_types": [tname],
        "adversarial": False, "user": prow["user"],
        "calls": calls, "label_surfaces": {gold: label_surface(gold)}, "answer": answer,
        "thinking_segments": [prow["organic_kept"], thinking_tail], "thinking_long": reasoning_long,
        "target_text_short": full_short, "target_text_long": full_long,
        "masked_spans_short": masked_spans_short,
        "tokens_short": acct_short, "tokens_long": acct_long,
        "delta_supervised": acct_long["tokens_supervised"] - acct_short["tokens_supervised"],
        "delta_total": (acct_long["tokens_total"] - acct_long["tokens_prompt_masked"]) -
                        (acct_short["tokens_total"] - acct_short["tokens_prompt_masked"]),
        "organic_thinking_tokens": organic_tok, "hybrid_thinking_tokens": hybrid_tok,
        "saved_tokens": organic_tok - hybrid_tok,
        "splice_char": prow["splice_char"], "gold_mentioned": mentioned,
    }
    return row, mentioned


def build2(args):
    prefixes_path = args.prefixes if os.path.isabs(args.prefixes) else os.path.join(ROOT, args.prefixes)
    conts_path = args.continuations if os.path.isabs(args.continuations) else os.path.join(ROOT,
                                                                                              args.continuations)
    out_path = args.out if os.path.isabs(args.out) else os.path.join(ROOT, args.out)

    prefixes = {}
    with open(prefixes_path, encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rec = json.loads(line)
                prefixes[rec["id"]] = rec
    conts = {}
    with open(conts_path, encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rec = json.loads(line)
                conts[rec["id"]] = rec
    if args.limit:
        prefixes = dict(list(prefixes.items())[:args.limit])
    print(f"loaded {len(prefixes)} prefixes from {args.prefixes}, {len(conts)} continuations from "
          f"{args.continuations}")

    canonical, canon_errs = load_canonical(os.path.join(ROOT, SUITE))
    if canon_errs:
        raise SystemExit(f"load_canonical errors: {canon_errs}")
    tok = get_tokenizer(args.model, args.revision)

    drop_reasons = collections.Counter()
    kept = []
    n_mentioned = n_checked = 0
    for rid, prow in prefixes.items():
        crow = conts.get(rid)
        if crow is None:
            drop_reasons["no_continuation"] += 1
            continue
        if not crow.get("finished"):
            drop_reasons["continuation_not_finished"] += 1
            continue
        cont_text = crow.get("continuation") or ""
        if not cont_text:
            drop_reasons["empty_continuation"] += 1
            continue
        try:
            row, mentioned = build2_row(tok, prow, cont_text, canonical)
        except ValueError as e:
            drop_reasons[str(e).split(":", 1)[0]] += 1
            continue
        n_checked += 1
        n_mentioned += mentioned
        kept.append(row)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        for r in kept:
            f.write(json.dumps(r) + "\n")

    print(f"\nbuild2: {len(kept)}/{len(prefixes)} rows kept -> {out_path}")
    print(f"  dropped: {sum(drop_reasons.values())}, by reason: {dict(drop_reasons)}")
    if n_checked:
        print(f"  gold label surface mentioned in continuation (thinking tail + answer): "
              f"{n_mentioned}/{n_checked} ({n_mentioned / n_checked:.1%}) -- logged only, NOT a drop "
              f"filter; if it HAD been applied as a drop filter, {n_checked - n_mentioned} additional "
              f"row(s) would have been dropped")
    if kept:
        org = [r["organic_thinking_tokens"] for r in kept]
        hyb = [r["hybrid_thinking_tokens"] for r in kept]
        saved = [r["saved_tokens"] for r in kept]
        mean_org, mean_hyb = sum(org) / len(org), sum(hyb) / len(hyb)
        mean_saved = sum(saved) / len(saved)
        print(f"\n  thinking tokens: organic mean {mean_org:.1f}, hybrid mean {mean_hyb:.1f}, "
              f"saved mean {mean_saved:.1f} ({mean_saved / mean_org:.1%})")
        print("\n  3 decoded examples (around the splice AND the start of the continuation):")
        for r in kept[:3]:
            trig = TRIGGER_FOR[r["decision_types"][0]]
            idx = r["target_text_short"].find(trig)
            lo, hi = max(0, idx - 150), idx + len(trig) + 300
            print(f"\n    {r['id']} splice_char={r['splice_char']} saved={r['saved_tokens']} "
                  f"gold_mentioned={r['gold_mentioned']}:")
            print(f"    ...{r['target_text_short'][lo:hi]!r}...")
    return kept


# ---------------------------------------------------------------------------
# tailprefix mode (v3 fix): the real continuation run (oracle/phase7r-hybrid-continuations.jsonl, see
# scripts/continue_phase7r_hybrid.py) showed the base model does NOT stop deliberating after the injected
# `<|result|>gold<|/result|>` -- it keeps re-analysing (hybrid thinking 394 tok vs organic 358, a NEGATIVE
# saving). Fix: append a short templated TAIL naming the result, then the model's OWN thinking-close
# marker (mirrored byte-for-byte off real organic raw_text -- see the inspection in this module's dev
# notes: the close marker directly follows the preceding sentence with NO extra newline, e.g.
# "...based on desired tone.<channel|>Here"), so the prefill FORCE-CLOSES the thinking channel and the
# base model can only continue by generating the visible answer.
# ---------------------------------------------------------------------------

def tailprefix_mode(args):
    prefixes_path = args.prefixes if os.path.isabs(args.prefixes) else os.path.join(ROOT, args.prefixes)
    out_path = args.out if os.path.isabs(args.out) else os.path.join(ROOT, args.out)

    rows = [json.loads(l) for l in open(prefixes_path, encoding="utf-8") if l.strip()]
    if args.limit:
        rows = rows[:args.limit]
    print(f"loaded {len(rows)} prefix rows from {args.prefixes}")

    out_rows = []
    for row in rows:
        tail_text = tail_for(row["id"], row["gold_label"])
        out = dict(row)
        out["prefix_text_notail"] = row["prefix_text"]
        out["tail_text"] = tail_text
        out["prefix_text"] = row["prefix_text"] + tail_text + THINK_CLOSE
        out_rows.append(out)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        for r in out_rows:
            f.write(json.dumps(r) + "\n")

    print(f"\ntailprefix: {len(out_rows)} rows -> {out_path}")
    if out_rows:
        print("  3 examples (tail of prefix_text, around the forced close):")
        for r in out_rows[:3]:
            print(f"\n    {r['id']} tail={r['tail_text']!r}:")
            print(f"    ...{r['prefix_text'][-250:]!r}")
    return out_rows


# ---------------------------------------------------------------------------
# build3 mode (rule v3): join tailprefix rows + answer-only continuations (scripts/continue_phase7r_hybrid.py
# run on the tailprefix file -- the model now generates ONLY the visible answer, since the prefill already
# closed the thinking channel) into final training rows, same schema as build2's output. Plus unchanged
# organic control rows (kind != "decision") from --organic, so the model also learns NOT to fire the
# trigger on ordinary turns.
# ---------------------------------------------------------------------------

def build3_row(tok, prow, cont_text, canonical):
    """-> (row dict, gold_mentioned: bool, contradiction: bool) or raises ValueError for a drop condition
    the caller matches on message prefix (keeps the drop-reason bookkeeping in one place, in build3())."""
    if "<|decide:" in cont_text:
        raise ValueError("retrigger: continuation contains a second '<|decide:' trigger")
    if THINK_CLOSE in cont_text:
        raise ValueError("duplicate_close: continuation re-closes the thinking channel (already closed "
                          "in the prefill)")
    if THINK_OPEN in cont_text:
        raise ValueError("malformed_channel: continuation reopens the thinking channel")

    answer = _strip_pad_and_turn(cont_text)
    if not answer:
        raise ValueError("empty_answer: continuation has no visible answer")

    tname, gold = prow["type"], prow["gold_label"]
    instr, _opts = canonical[tname]
    options_kv = prow["options_with_descriptions"]
    options = [option_text(k, d) for k, d in options_kv]
    calls = [{"type": tname, "instruction": instr, "options": options, "gold_label": gold}]

    tail_text = prow["tail_text"]
    reasoning_short = build_reasoning(calls, [prow["organic_kept"], tail_text])
    reasoning_long = prow["thinking_long"]

    full_short, plen_short = render_hybrid(tok, prow["user"], reasoning_short, answer)
    full_long, plen_long = render_hybrid(tok, prow["user"], reasoning_long, prow["organic_answer"])

    injected = injected_spans_typed(full_short)
    if injected_spans_typed(full_long):
        raise ValueError(f"{prow['id']}: thinking_long contains trigger/result markers")
    if len(injected) != 1:
        raise ValueError(f"bad_injected_spans: expected 1 injected span, found {len(injected)}")

    acct_short = token_accounting(tok, full_short, plen_short, injected)
    acct_long = token_accounting(tok, full_long, plen_long, [])
    masked_spans_short = [[0, plen_short]] + [[s, e] for s, e in injected]

    organic_tok = decoded_think_tokens(tok, reasoning_long)
    hybrid_tok = decoded_think_tokens(tok, reasoning_short)

    answer_l = answer.lower()
    gold_mentioned = _word_hit(leak_terms(gold), answer_l)
    other_mentioned = any(k != gold and _word_hit(leak_terms(k), answer_l) for k, _d in options_kv)
    contradiction = (not gold_mentioned) and other_mentioned

    row = {
        "id": prow["id"], "kind": "call", "source": "H", "decision_types": [tname],
        "adversarial": False, "user": prow["user"],
        "calls": calls, "label_surfaces": {gold: label_surface(gold)}, "answer": answer,
        "thinking_segments": [prow["organic_kept"], tail_text], "thinking_long": reasoning_long,
        "target_text_short": full_short, "target_text_long": full_long,
        "masked_spans_short": masked_spans_short,
        "tokens_short": acct_short, "tokens_long": acct_long,
        "delta_supervised": acct_long["tokens_supervised"] - acct_short["tokens_supervised"],
        "delta_total": (acct_long["tokens_total"] - acct_long["tokens_prompt_masked"]) -
                        (acct_short["tokens_total"] - acct_short["tokens_prompt_masked"]),
        "organic_thinking_tokens": organic_tok, "hybrid_thinking_tokens": hybrid_tok,
        "saved_tokens": organic_tok - hybrid_tok,
        "splice_char": prow["splice_char"], "tail_text": tail_text, "gold_mentioned": gold_mentioned,
    }
    return row, gold_mentioned, contradiction


def build3(args):
    prefixes_path = args.prefixes if os.path.isabs(args.prefixes) else os.path.join(ROOT, args.prefixes)
    answers_path = args.answers if os.path.isabs(args.answers) else os.path.join(ROOT, args.answers)
    organic_path = args.organic if os.path.isabs(args.organic) else os.path.join(ROOT, args.organic)
    out_path = args.out if os.path.isabs(args.out) else os.path.join(ROOT, args.out)

    prefixes = {}
    with open(prefixes_path, encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rec = json.loads(line)
                prefixes[rec["id"]] = rec
    answers = {}
    with open(answers_path, encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rec = json.loads(line)
                answers[rec["id"]] = rec
    if args.limit:
        prefixes = dict(list(prefixes.items())[:args.limit])
    print(f"loaded {len(prefixes)} tailprefix rows from {args.prefixes}, {len(answers)} answer "
          f"generations from {args.answers}")

    canonical, canon_errs = load_canonical(os.path.join(ROOT, SUITE))
    if canon_errs:
        raise SystemExit(f"load_canonical errors: {canon_errs}")
    tok = get_tokenizer(args.model, args.revision)

    drop_reasons = collections.Counter()
    call_rows = []
    n_checked = n_gold_mentioned = n_contradiction = 0
    for rid, prow in prefixes.items():
        crow = answers.get(rid)
        if crow is None:
            drop_reasons["no_answer"] += 1
            continue
        if not crow.get("finished"):
            drop_reasons["answer_not_finished"] += 1
            continue
        cont_text = crow.get("continuation") or ""
        if not cont_text:
            drop_reasons["empty_continuation"] += 1
            continue
        try:
            row, gold_mentioned, contradiction = build3_row(tok, prow, cont_text, canonical)
        except ValueError as e:
            drop_reasons[str(e).split(":", 1)[0]] += 1
            continue
        n_checked += 1
        n_gold_mentioned += gold_mentioned
        n_contradiction += contradiction
        if contradiction:
            drop_reasons["contradiction"] += 1
            continue
        call_rows.append(row)

    organic_rows = [json.loads(l) for l in open(organic_path, encoding="utf-8") if l.strip()]
    control_drop = collections.Counter()
    control_rows = []
    for row in organic_rows:
        if row["kind"] == "decision":
            continue
        if not row.get("finished"):
            control_drop["not_finished"] += 1
            continue
        if not row.get("thinking") or not row.get("answer"):
            control_drop["empty_thinking_or_answer"] += 1
            continue
        if row.get("n_thinking_tokens", 0) > MAX_THINK_TOKENS:
            control_drop["over_max_think_tokens"] += 1
            continue
        control_rows.append(build_hybrid_row(tok, row, canonical))

    kept = call_rows + control_rows
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        for r in kept:
            f.write(json.dumps(r) + "\n")

    print(f"\nbuild3: {len(kept)} rows -> {out_path} ({len(call_rows)} call, {len(control_rows)} control)")
    print(f"  call drop reasons: {dict(drop_reasons)}")
    print(f"  control drop reasons (from {len(organic_rows)} organic rows): {dict(control_drop)}")
    if n_checked:
        print(f"  gold label surface mentioned in answer: {n_gold_mentioned}/{n_checked} "
              f"({n_gold_mentioned / n_checked:.1%})")
        print(f"  contradiction (answer names another option, not gold -- DROPPED): {n_contradiction}/"
              f"{n_checked} ({n_contradiction / n_checked:.1%})")

    if call_rows:
        org = [r["organic_thinking_tokens"] for r in call_rows]
        hyb = [r["hybrid_thinking_tokens"] for r in call_rows]
        saved = [r["saved_tokens"] for r in call_rows]
        mean_org, mean_hyb = sum(org) / len(org), sum(hyb) / len(hyb)
        mean_saved = sum(saved) / len(saved)
        print(f"\n  call rows thinking tokens: organic mean {mean_org:.1f}, hybrid mean {mean_hyb:.1f}, "
              f"saved mean {mean_saved:.1f} ({mean_saved / mean_org:.1%})")

        ans_tok = [len(tok(r["answer"], add_special_tokens=False)["input_ids"]) for r in call_rows]
        org_ans_tok = [len(tok(prefixes[r["id"]]["organic_answer"], add_special_tokens=False)["input_ids"])
                       for r in call_rows]
        mean_ans, mean_org_ans = sum(ans_tok) / len(ans_tok), sum(org_ans_tok) / len(org_ans_tok)
        mean_total_hyb, mean_total_org = mean_hyb + mean_ans, mean_org + mean_org_ans
        print(f"  mean answer tokens: hybrid {mean_ans:.1f}, organic {mean_org_ans:.1f}")
        print(f"  mean total decoded tokens (thinking+answer): hybrid {mean_total_hyb:.1f}, "
              f"organic {mean_total_org:.1f} ({(mean_total_org - mean_total_hyb) / mean_total_org:.1%} "
              f"saving)")

        print("\n  3 decoded examples (around the splice AND the forced close/answer):")
        for r in call_rows[:3]:
            trig = TRIGGER_FOR[r["decision_types"][0]]
            idx = r["target_text_short"].find(trig)
            lo, hi = max(0, idx - 100), idx + len(trig) + 350
            print(f"\n    {r['id']} splice_char={r['splice_char']} saved={r['saved_tokens']} "
                  f"gold_mentioned={r['gold_mentioned']}:")
            print(f"    ...{r['target_text_short'][lo:hi]!r}...")
    return kept


# ---------------------------------------------------------------------------
# validate (rule 5)
# ---------------------------------------------------------------------------

def validate(args):
    rows_path = args.rows if os.path.isabs(args.rows) else os.path.join(ROOT, args.rows)
    if args.dev and "dev" not in os.path.basename(rows_path).lower():
        raise SystemExit(f"--dev requires --rows to contain 'dev' in its filename (got {rows_path!r})")
    rows = [json.loads(l) for l in open(rows_path, encoding="utf-8") if l.strip()]
    print(f"validate: {len(rows)} rows from {args.rows}")

    fails = []

    def bad(rid, msg):
        fails.append(f"{rid}: {msg}")

    for r in rows:
        rid = r["id"]
        full = r["target_text_short"]
        n_calls = len(r["calls"])
        n_trigger = sum(full.count(t) for t in TRIGGER_FOR.values())
        if r["kind"] == "call":
            if n_trigger != 1 or n_calls != 1:
                bad(rid, f"decision row has {n_trigger} triggers / {n_calls} calls, expected exactly 1 each")
            c = r["calls"][0] if r["calls"] else {}
            if c.get("type") not in SHIPPED_TYPES:
                bad(rid, f"call type {c.get('type')!r} not a shipped type")
            spans = injected_spans_typed(full)
            if len(spans) != 1:
                bad(rid, f"{len(spans)} injected spans, expected 1")
            else:
                s, e = spans[0]
                trig = TRIGGER_FOR[c.get("type")]
                trig_idx = full.find(trig)
                instr_start = trig_idx + len(trig)
                if s != instr_start:
                    bad(rid, f"injected span start {s} != end of trigger {instr_start}")
                want_prefix = f"{c.get('instruction')} [{', '.join(c.get('options', []))}]{RESULT_OPEN}"
                if full[s:s + len(want_prefix)] != want_prefix:
                    bad(rid, "injected span does not start with INSTR [options]<|result|>")
                result_text = full[s + len(want_prefix):e - len(RESULT_CLOSE)]
                if result_text != c.get("gold_label"):
                    bad(rid, f"result text {result_text!r} != gold_label {c.get('gold_label')!r}")
                if full[e - len(RESULT_CLOSE):e] != RESULT_CLOSE:
                    bad(rid, "injected span does not end with <|/result|>")
        else:
            if n_trigger != 0 or n_calls != 0:
                bad(rid, f"control row has {n_trigger} triggers / {n_calls} calls, expected 0")

        if r["target_text_long"].count("<|decide:") or RESULT_OPEN in r["target_text_long"]:
            bad(rid, "target_text_long contains trigger/result markers")
        if full.count("<|think|>\n") != 1:
            bad(rid, f"target_text_short has {full.count(chr(10).join(['<|think|>','']))} "
                     f"'<|think|>' markers, expected exactly 1 (no duplication)")

    ids = [r["id"] for r in rows]
    if len(set(ids)) != len(ids):
        fails.append(f"duplicate ids: {[k for k, v in collections.Counter(ids).items() if v > 1]}")

    # encode_think masking check, same contract as scripts/test_encode_think.py
    from scripts.train_phase7 import encode_think
    tok = get_tokenizer(args.model, args.revision)
    n_mask_checked = n_mask_failed = 0
    for r in rows:
        for variant in ("short", "long"):
            enc = encode_think(tok, r, max_len=4096, variant=variant, user_turn_cap=10_000)
            if enc is None:
                continue
            text = r[f"target_text_{variant}"]
            offs = tok(text, return_offsets_mapping=True, add_special_tokens=False)["offset_mapping"]
            prompt_end = r["masked_spans_short"][0][1]
            spans = r["masked_spans_short"] if variant == "short" else [[0, prompt_end]]
            n_mask_checked += 1
            ok = True
            for i, (a, b) in enumerate(offs):
                should_mask = any(a < e and b > s for s, e in spans)
                is_masked = enc["labels"][i].item() == -100
                if should_mask != is_masked:
                    ok = False
                    break
            if r["kind"] == "call" and variant == "short":
                trig = f"<|decide:{r['calls'][0]['type']}|>"
                idx = text.find(trig)
                trig_end = idx + len(trig)
                trig_labels = [enc["labels"][i].item() for i, (a, b) in enumerate(offs)
                               if a < trig_end and b > idx]
                if not trig_labels or all(l == -100 for l in trig_labels):
                    ok = False
            last_turn = text.rfind("<turn|>")
            turn_end = last_turn + len("<turn|>")
            turn_labels = [enc["labels"][i].item() for i, (a, b) in enumerate(offs)
                           if a < turn_end and b > last_turn]
            if not turn_labels or any(l == -100 for l in turn_labels):
                ok = False
            if not ok:
                n_mask_failed += 1
                bad(r["id"], f"encode_think masking check failed ({variant})")
    print(f"encode_think masking check: {n_mask_checked} (row, variant) pairs checked, "
          f"{n_mask_failed} failed")

    if fails:
        print(f"\nFAILED: {len(fails)} problem(s)")
        for fl in fails[:50]:
            print(f"  - {fl}")
        return 1
    print("all checks passed")
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = ap.add_subparsers(dest="mode")

    p_build = sub.add_parser("build")
    p_build.add_argument("--organic", required=True)
    p_build.add_argument("--out", required=True)
    p_build.add_argument("--extract", default=None)
    p_build.add_argument("--dev", action="store_true")
    p_build.add_argument("--limit", type=int, default=None)
    p_build.add_argument("--model", default=MODEL)
    p_build.add_argument("--revision", default=REVISION)

    p_prefix = sub.add_parser("prefix")
    p_prefix.add_argument("--organic", required=True)
    p_prefix.add_argument("--out", required=True)
    p_prefix.add_argument("--limit", type=int, default=None)
    p_prefix.add_argument("--model", default=MODEL)
    p_prefix.add_argument("--revision", default=REVISION)

    p_build2 = sub.add_parser("build2")
    p_build2.add_argument("--prefixes", required=True)
    p_build2.add_argument("--continuations", required=True)
    p_build2.add_argument("--out", required=True)
    p_build2.add_argument("--limit", type=int, default=None)
    p_build2.add_argument("--model", default=MODEL)
    p_build2.add_argument("--revision", default=REVISION)

    p_tail = sub.add_parser("tailprefix")
    p_tail.add_argument("--prefixes", required=True)
    p_tail.add_argument("--out", required=True)
    p_tail.add_argument("--limit", type=int, default=None)

    p_build3 = sub.add_parser("build3")
    p_build3.add_argument("--prefixes", required=True)
    p_build3.add_argument("--answers", required=True)
    p_build3.add_argument("--organic", required=True)
    p_build3.add_argument("--out", required=True)
    p_build3.add_argument("--limit", type=int, default=None)
    p_build3.add_argument("--model", default=MODEL)
    p_build3.add_argument("--revision", default=REVISION)

    p_val = sub.add_parser("validate")
    p_val.add_argument("--rows", required=True)
    p_val.add_argument("--dev", action="store_true")
    p_val.add_argument("--model", default=MODEL)
    p_val.add_argument("--revision", default=REVISION)

    args = ap.parse_args()
    if args.mode == "build":
        build(args)
        return 0
    if args.mode == "prefix":
        prefix_mode(args)
        return 0
    if args.mode == "build2":
        build2(args)
        return 0
    if args.mode == "tailprefix":
        tailprefix_mode(args)
        return 0
    if args.mode == "build3":
        build3(args)
        return 0
    if args.mode == "validate":
        return validate(args)
    ap.print_help()
    return 1


if __name__ == "__main__":
    sys.exit(main())
